# What is CSV(Comma Separated Values)?
# Comma Separated Values format is the most common import and export format for spreadsheets and databases.
# The CSV module implements classes to read and write tabular data in CSV format.
# Coder like say: write this data in the format preferred by Excel.
# Coder like say: read data from this file which was generated by Excel, without knowing the precise details of the CSV
# format used by EXCEL.

# The csv module's reader and writer objects read and write sequences.

